# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  justicetechnicalassestment:
    image: justicetechnicalassestment
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5170:5170
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
